#!/usr/bin/env python

import os
import sys

from cana.data import Verb
from cana.ui import VerbWindow
from cana.app import Application

if __name__ == '__main__':
    app = Application()

    if len(sys.argv) > 1:
        verblist = sys.argv[1:]
    else:
        verblist = os.listdir('verbs')

    verbs = []
    for f in verblist:
        verbs.append(Verb(f))

    # TODO: add this to the activate callback of the application
    window = VerbWindow(verbs)
    window.fullscreen()
    app.add_window(window)
    window.show()

    app.run(sys.argv)
