#!/usr/bin/env python

import os
import sys

from gi.repository import Gio

import cana.data
from cana.ui import VerbWindow
from cana.app import Application

def parse(verblist):
    verbs = []
    for f in verblist:
        v = cana.data.parse(f)
        if v:
            verbs.append(v)

    return verbs

def activate(app, verbs=None):
    if verbs is None:
        verbs = parse(os.listdir('verbs'))

    try:
        window = VerbWindow(verbs)
    except IndexError:
        print 'no verbs found'
        return

    window.fullscreen()
    app.add_window(window)
    window.show()

def opened(app, files, hint, data):
    verbs = parse([x.get_basename() for x in files])
    activate(app, verbs)

if __name__ == '__main__':
    app = Application()
    app.set_flags(Gio.ApplicationFlags.HANDLES_OPEN)

    app.connect('activate', activate)
    app.connect('open', opened)

    app.run(sys.argv)
