#!/usr/bin/env python

import sys

from cana.data import Data
from cana.ui import TestWindow
from cana.app import Application

if __name__ == '__main__':
    data = Data('words')

    app = Application()

    # TODO: add this to the activate callback of the application
    window = TestWindow(data.italian())
    app.add_window(window)
    window.show()

    app.run(sys.argv)
