#!/usr/bin/env python

import sys

from cana.data import Data
from cana.ui import TestWindow
from cana.app import Application

def activate(app, data):
    window = TestWindow(data.italian())
    app.add_window(window)
    window.show()

if __name__ == '__main__':
    data = Data('words')

    app = Application()
    app.connect('activate', activate, data)

    app.run(sys.argv)
